# Tell Travis CI we're using PHP
language: php

# Opt to use Travis container-based environment.
sudo: false

# Newer versions like trusty don't have PHP 5.2 or 5.3
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/phpunit-bin
    - $HOME/deployment-targets

install:
  - if [[ $DEV_LIB_SKIP =~ composer ]]; then composer install --no-dev; fi
  - nvm install 6 && nvm use 6
  - npm install
  - export DEV_LIB_PATH=node_modules/wp-dev-lib
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

jobs:
  include:
    - stage: test
      php: "7.2"
      env: WP_VERSION=trunk
    - php: "5.2"
      env: WP_VERSION=latest DEV_LIB_SKIP=composer,phpcs
    - php: "5.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=composer,phpcs
    - php: "5.4"
      env: WP_VERSION=4.7    DEV_LIB_SKIP=composer,phpcs
    - php: "5.5"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "5.6"
      env: WP_VERSION=4.8    DEV_LIB_SKIP=phpcs
    - php: "5.6"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.0"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.1"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
